server:
  port: 9090
spring:
  application:
    name: springbootadminserver
  boot:
    admin:
      notify:
        mail:
          to: 644875343@qq.com
      discovery:
        ignored-services: consul
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: management.context-path=/foo,health.path=/ping,user.name=user,user.password=password
    zookeeper:
      connect-string: localhost:2181
      discovery:
        metadata:
          management.context-path: /foo
          health.path: /ping
          user.name: user
          user.password: password
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  security:
    user:
      name: admin
      password: test
# eureka配置
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
      user.name: admin
      user.password: test
    status-page-url-path: /actuator/info
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
      path-mapping:
        health: /ping
      base-path: /foo
  endpoint:
    health:
      show-details: always